# Generated by Django 5.1.5 on 2025-06-24 12:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to=app.models.post_image_path),
        ),
    ]
