# Generated by Django 5.1.5 on 2025-06-25 09:06

import app.models
import app.nextcloud_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(storage=app.nextcloud_storage.NextcloudWebDAVStorage, upload_to=app.models.post_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=app.nextcloud_storage.NextcloudWebDAVStorage, upload_to=app.models.banner_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=app.nextcloud_storage.NextcloudWebDAVStorage, upload_to=app.models.profile_photo_path),
        ),
        migrations.AlterField(
            model_name='videos',
            name='tumbnail',
            field=models.ImageField(storage=app.nextcloud_storage.NextcloudWebDAVStorage, upload_to=app.models.thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(storage=app.nextcloud_storage.NextcloudWebDAVStorage, upload_to=app.models.video_upload_path),
        ),
    ]
